ALTER TABLE products DROP CONSTRAINT products_category_check;
ALTER TABLE products ADD CONSTRAINT products_category_check CHECK(category IN ('Snacks','Sweet treats','Bakery','Drinks','Coffee & cups','Sandwiches','Salads','Hot food','Fruit'));
UPDATE products SET category='Bakery' WHERE id='butter-croissant';
INSERT INTO products(id,name,description,category,price_cents,image,dietary,position) VALUES
('sea-salt-chips','Sea salt chips','Crispy kettle potato chips. 45 g bag.','Snacks',249,'/market/sea-salt-chips.svg','[]',13),
('bbq-chips','Smoky BBQ chips','Smoky, savory potato chips. 45 g bag.','Snacks',249,'/market/bbq-chips.svg','[]',14),
('cheddar-popcorn','Cheddar popcorn','Air-popped corn with cheddar seasoning. 35 g bag.','Snacks',299,'/market/cheddar-popcorn.svg','[]',15),
('mini-pretzels','Mini pretzels','Crunchy, salted pretzel twists. 50 g bag.','Snacks',229,'/market/mini-pretzels.svg','[]',16),
('roasted-almonds','Roasted almonds','Dry-roasted salted almonds. 40 g pouch.','Snacks',349,'/market/roasted-almonds.svg','[]',17),
('trail-mix','Trail mix','Peanuts, raisins and chocolate pieces. 50 g pouch.','Snacks',329,'/market/trail-mix.svg','[]',18),
('beef-jerky','Original beef jerky','Smoky beef strips in a resealable 30 g pouch.','Snacks',499,'/market/beef-jerky.svg','[]',19),
('tortilla-chips','Tortilla chips','Golden corn chips with a salty crunch. 45 g bag.','Snacks',259,'/market/tortilla-chips.svg','[]',20),
('milk-chocolate','Milk chocolate bar','Smooth milk chocolate, individually wrapped. 45 g.','Sweet treats',229,'/market/milk-chocolate.svg','[]',21),
('dark-chocolate','Dark chocolate bar','Rich 70% cocoa chocolate. 40 g bar.','Sweet treats',279,'/market/dark-chocolate.svg','[]',22),
('peanut-caramel','Peanut caramel bar','Roasted peanuts, soft caramel and chocolate. 50 g.','Sweet treats',249,'/market/peanut-caramel.svg','[]',23),
('fruit-gummies','Fruit gummies','Colorful chewy fruit-flavored candy. 60 g pouch.','Sweet treats',199,'/market/fruit-gummies.svg','[]',24),
('mint-gum','Fresh mint gum','A pocket-size pack of mint chewing gum. 14 pieces.','Sweet treats',189,'/market/mint-gum.svg','[]',25),
('peppermint-mints','Peppermint mints','Crisp peppermint sweets in a small tin. 25 g.','Sweet treats',199,'/market/peppermint-mints.svg','[]',26),
('blueberry-muffin','Blueberry muffin','A soft blueberry muffin in an individual wrapper.','Bakery',349,'/market/blueberry-muffin.svg','[]',27),
('chocolate-muffin','Chocolate muffin','Double chocolate muffin, wrapped for the road.','Bakery',349,'/market/chocolate-muffin.svg','[]',28),
('glazed-donut','Glazed donut','A soft ring donut with a classic sugar glaze.','Bakery',279,'/market/glazed-donut.svg','[]',29),
('cinnamon-roll','Cinnamon roll','Swirled cinnamon pastry with vanilla icing.','Bakery',399,'/market/cinnamon-roll.svg','[]',30),
('banana-bread','Banana bread slice','A thick, individually wrapped slice of banana loaf.','Bakery',329,'/market/banana-bread.svg','[]',31),
('cheese-danish','Cheese danish','Flaky pastry with a sweet cream cheese center.','Bakery',379,'/market/cheese-danish.svg','[]',32),
('everything-bagel','Everything bagel','Toasted-style bagel with sesame, onion and poppy seeds.','Bakery',299,'/market/everything-bagel.svg','[]',33),
('classic-cola','Classic cola','Chilled cola in a 330 ml can.','Drinks',249,'/market/classic-cola.svg','[]',34),
('zero-cola','Zero sugar cola','Zero-sugar cola in a chilled 330 ml can.','Drinks',249,'/market/zero-cola.svg','[]',35),
('citrus-energy','Citrus energy drink','Caffeinated citrus energy drink. 250 ml can.','Drinks',349,'/market/citrus-energy.svg','[]',36),
('orange-juice','Orange juice','Bright orange juice in a 300 ml bottle.','Drinks',329,'/market/orange-juice.svg','[]',37),
('sports-drink','Blue sports drink','Blue berry-flavored sports drink. 500 ml bottle.','Drinks',299,'/market/sports-drink.svg','[]',38),
('still-water','Still spring water','Chilled spring water in a 500 ml bottle.','Drinks',199,'/market/still-water.svg','[]',39),
('zero-lager','Zero-alcohol lager','Crisp lager-style malt drink. 0.0% alcohol, 330 ml can.','Drinks',399,'/market/zero-lager.svg','[]',40),
('berry-seltzer','Berry seltzer','Berry sparkling water. Zero alcohol, 330 ml can.','Drinks',279,'/market/berry-seltzer.svg','[]',41),
('house-coffee','House coffee','A smooth medium roast in a 12 oz takeaway cup.','Coffee & cups',279,'/market/house-coffee.svg','[]',42),
('large-coffee','Large house coffee','Our medium roast in a 16 oz lidded cup.','Coffee & cups',329,'/market/large-coffee.svg','[]',43),
('cappuccino','Cappuccino','Espresso and foamed milk in a 12 oz cup.','Coffee & cups',429,'/market/cappuccino.svg','[]',44),
('oat-latte','Oat milk latte','Espresso with oat drink in a 12 oz takeaway cup.','Coffee & cups',459,'/market/oat-latte.svg','[]',45),
('hot-chocolate','Hot chocolate','Rich cocoa with milk in a 12 oz cup.','Coffee & cups',399,'/market/hot-chocolate.svg','[]',46),
('english-tea','English breakfast tea','Black tea in a 12 oz lidded cup.','Coffee & cups',249,'/market/english-tea.svg','[]',47),
('iced-tea','Lemon iced tea','Chilled black tea with lemon in a 16 oz cup.','Coffee & cups',299,'/market/iced-tea.svg','[]',48),
('fountain-lemonade','Fountain lemonade','Refreshing lemon soda in a 20 oz fountain cup.','Coffee & cups',279,'/market/fountain-lemonade.svg','[]',49),
('turkey-wrap','Turkey & cheddar wrap','Turkey, cheddar and crisp lettuce in a wrapped tortilla.','Sandwiches',799,'/market/turkey-wrap.svg','[]',50),
('veggie-wrap','Hummus veggie wrap','Hummus, carrots and crisp greens in a soft tortilla.','Sandwiches',749,'/market/veggie-wrap.svg','[]',51),
('ham-swiss','Ham & Swiss sandwich','Ham and Swiss cheese in a clear deli sandwich pack.','Sandwiches',799,'/market/ham-swiss.svg','[]',52),
('tuna-sandwich','Tuna salad sandwich','Tuna salad and leaves on sliced seeded bread.','Sandwiches',779,'/market/tuna-sandwich.svg','[]',53),
('egg-sandwich','Egg salad sandwich','Creamy egg salad on soft bread, ready to go.','Sandwiches',649,'/market/egg-sandwich.svg','[]',54),
('caesar-bowl','Chicken Caesar bowl','Chicken, romaine, croutons and Caesar dressing in a clear bowl.','Salads',1099,'/market/caesar-bowl.svg','[]',55),
('quinoa-bowl','Quinoa rainbow bowl','Quinoa, roasted vegetables and chickpeas in a clear bowl.','Salads',999,'/market/quinoa-bowl.svg','[]',56),
('greek-salad','Greek salad bowl','Tomato, cucumber, olives and feta in a grab-and-go bowl.','Salads',949,'/market/greek-salad.svg','[]',57),
('pasta-salad','Pesto pasta salad','Pasta, basil pesto and cherry tomatoes in a deli tub.','Salads',849,'/market/pasta-salad.svg','[]',58),
('california-roll','California sushi roll','Eight pieces of crab-style and avocado sushi in a clear tray.','Salads',999,'/market/california-roll.svg','[]',59),
('veggie-sushi','Veggie sushi pack','Eight cucumber, carrot and avocado rolls in a clear tray.','Salads',899,'/market/veggie-sushi.svg','[]',60),
('classic-hot-dog','Classic hot dog','A warm frankfurter in a soft bun with mustard.','Hot food',499,'/market/classic-hot-dog.svg','[]',61),
('cheeseburger','Classic cheeseburger','Beef patty, melted cheese and pickles in a soft bun.','Hot food',799,'/market/cheeseburger.svg','[]',62),
('veggie-burger','Veggie burger','Vegetable patty, tomato and crisp leaves in a bun.','Hot food',799,'/market/veggie-burger.svg','[]',63),
('cheese-pizza','Cheese pizza slice','A generous slice with tomato sauce and mozzarella.','Hot food',449,'/market/cheese-pizza.svg','[]',64),
('pepperoni-pizza','Pepperoni pizza slice','Mozzarella and pepperoni on a golden pizza slice.','Hot food',499,'/market/pepperoni-pizza.svg','[]',65),
('tenders-fries','Chicken tenders & fries','Three chicken tenders with a side of golden fries.','Hot food',1099,'/market/tenders-fries.svg','[]',66),
('mac-cheese','Mac & cheese bowl','Creamy macaroni and cheese in a warm food bowl.','Hot food',649,'/market/mac-cheese.svg','[]',67),
('breakfast-burrito','Breakfast burrito','Scrambled eggs, potato and cheese in a warm tortilla.','Hot food',749,'/market/breakfast-burrito.svg','[]',68),
('red-apple','Crisp red apple','One fresh whole red apple.','Fruit',129,'/market/red-apple.svg','[]',69),
('green-apple','Green apple','One crisp, tart green apple.','Fruit',129,'/market/green-apple.svg','[]',70),
('banana','Banana','One fresh banana, ready for your next break.','Fruit',99,'/market/banana.svg','[]',71),
('orange','Sweet orange','One whole orange with a bright citrus aroma.','Fruit',139,'/market/orange.svg','[]',72),
('pear','Fresh pear','One ripe green pear.','Fruit',159,'/market/pear.svg','[]',73),
('grapes-cup','Grape cup','A clear 150 g cup of washed seedless grapes.','Fruit',349,'/market/grapes-cup.svg','[]',74),
('watermelon-cup','Watermelon cup','Chilled watermelon pieces in a 180 g clear cup.','Fruit',379,'/market/watermelon-cup.svg','[]',75),
('mixed-fruit','Mixed fruit cup','Melon, pineapple and grapes in a 180 g cup.','Fruit',399,'/market/mixed-fruit.svg','[]',76);
